function  Book_AddFiles()
{
  this.fNewFile("Introduction to eWebEditPro  ","introduc.htm");
  this.fNewFile("Using eWebEditPro  ","introdu2.htm");
  this.fNewFile("Organization of this Documentation  ","introdu3.htm");
  this.fNewFile("Creating a Simple Web Page  ","samplewe.htm");
  this.fNewFile("Your Finished Web Page  ","samplew2.htm");
  this.fNewFile("Creating the Sample Web Page  ","samplew3.htm");
  this.fNewFile("Toolbar Buttons  ","tableoft.htm");
  this.fNewFile("Selecting Text  ","tableof2.htm");
  this.fNewFile("Applying Formatting Attributes to Text  ","tableof3.htm");
  this.fNewFile("Table of Toolbar Buttons and Drop-Down Lists  ","tableof4.htm");
  this.fNewFile("Position Objects Options  ","tableof5.htm");
  this.fNewFile("Text Direction Options  ","tableof6.htm");
  this.fNewFile("Form Elements Toolbar  ","tableof7.htm");
  this.fNewFile("Buttons of the Form Elements Toolbar  ","tableof8.htm");
  this.fNewFile("Customizing Your Toolbar  ","customiz.htm");
  this.fNewFile("Removing Or Adding Menus  ","customi2.htm");
  this.fNewFile("Removing or Adding Menu Items  ","customi3.htm");
  this.fNewFile("Restoring Toolbars  ","customi4.htm");
  this.fNewFile("Rearranging the Menus on a Toolbar  ","customi5.htm");
  this.fNewFile("Creating a New Menu  ","customi6.htm");
  this.fNewFile("Moving a Menu Off the Toolbar  ","customi7.htm");
  this.fNewFile("Changing the Menu's Orientation  ","customi8.htm");
  this.fNewFile("The Context Sensitive Menu  ","contexts.htm");
  this.fNewFile("Using eWebEditPro's Advanced Features  ","introtou.htm");
  this.fNewFile("Copying from Other Applications  ","copya.htm");
  this.fNewFile("Finding and Replacing Text  ","finda.htm");
  this.fNewFile("Finding Text  ","find2.htm");
  this.fNewFile("Finding and Replacing Text  ","find3.htm");
  this.fNewFile("Additional Options on the Dialog Box  ","find4.htm");
  this.fNewFile("Specifying a Search Direction  ","find5.htm");
  this.fNewFile("Considering the Case of a Search Term  ","find6.htm");
  this.fNewFile("Whole Word Match  ","find7.htm");
  this.fNewFile("Checking Spelling  ","spellchb.htm");
  this.fNewFile("Disabling Script Blocking  ","spellch2.htm");
  this.fNewFile("Checking Spelling as You Type  ","spellch3.htm");
  this.fNewFile("Checking Spelling Upon Demand  ","spellch4.htm");
  this.fNewFile("Spell Checking Selected Text  ","spellch5.htm");
  this.fNewFile("Setting Spell Check Options  ","spellch6.htm");
  this.fNewFile("Editing in Microsoft Word  ","msworda.htm");
  this.fNewFile("Uploading an Image in a Microsoft Word Document  ","msword2.htm");
  this.fNewFile("Editing XML Documents  ","msword3.htm");
  this.fNewFile("Inserting Images  ","pictures.htm");
  this.fNewFile("Using the First Picture Properties Dialog Box  ","picture2.htm");
  this.fNewFile("Inserting a Picture from the Server  ","picture3.htm");
  this.fNewFile("Inserting a Picture from Your Computer  ","picture4.htm");
  this.fNewFile("Using the Second Media Selection Dialog Box  ","picture5.htm");
  this.fNewFile("Adjusting a Picture  ","picture6.htm");
  this.fNewFile("Pixels  ","picture7.htm");
  this.fNewFile("Setting a Border  ","picture8.htm");
  this.fNewFile("Aligning the Picture  ","picture9.htm");
  this.fNewFile("Resetting Width, Height, Border Thickness, and Alignment   ","pictur10.htm");
  this.fNewFile("Adding Space around the Picture  ","pictur11.htm");
  this.fNewFile("Editing the Picture's Title  ","pictur12.htm");
  this.fNewFile("The Options Button  ","pictur13.htm");
  this.fNewFile("Moving an Image to the Server  ","pictur14.htm");
  this.fNewFile("Deleting a Picture  ","pictur15.htm");
  this.fNewFile("Editing Images  ","imageedi.htm");
  this.fNewFile("Using WebImageFX  ","imageed2.htm");
  this.fNewFile("Saving the Image  ","imageed3.htm");
  this.fNewFile("Toolbar Buttons and Menu Commands  ","imageed4.htm");
  this.fNewFile("Blur  ","imageed5.htm");
  this.fNewFile("Brightness  ","imageed6.htm");
  this.fNewFile("Choose Color  ","imageed7.htm");
  this.fNewFile("Choose Font  ","imageed8.htm");
  this.fNewFile("Color Depth  ","imageed9.htm");
  this.fNewFile("Contrast  ","imagee10.htm");
  this.fNewFile("Copy  ","imagee11.htm");
  this.fNewFile("Create New  ","imagee12.htm");
  this.fNewFile("Crop  ","imagee13.htm");
  this.fNewFile("Delete  ","imagee14.htm");
  this.fNewFile("Dimensions  ","imagee15.htm");
  this.fNewFile("Exit  ","imagee16.htm");
  this.fNewFile("Freehand  ","imagee17.htm");
  this.fNewFile("Horizontal Flip  ","imagee18.htm");
  this.fNewFile("Image Info  ","imagee19.htm");
  this.fNewFile("Line  ","imagee20.htm");
  this.fNewFile("Open  ","imagee21.htm");
  this.fNewFile("Oval  ","imagee22.htm");
  this.fNewFile("Paste as New Image  ","imagee23.htm");
  this.fNewFile("Pointer Selection  ","imagee24.htm");
  this.fNewFile("Polygon  ","imagee25.htm");
  this.fNewFile("Rectangle  ","imagee26.htm");
  this.fNewFile("Redo  ","imagee27.htm");
  this.fNewFile("Reset Zoom Ratio  ","imagee28.htm");
  this.fNewFile("Rotate  ","imagee29.htm");
  this.fNewFile("Save  ","imagee30.htm");
  this.fNewFile("Save As  ","imagee31.htm");
  this.fNewFile("Select  ","imagee32.htm");
  this.fNewFile("Sharpen  ","imagee33.htm");
  this.fNewFile("Text  ","imagee34.htm");
  this.fNewFile("Thumbnail  ","imagee35.htm");
  this.fNewFile("Twain Acquire  ","imagee36.htm");
  this.fNewFile("Twain Source  ","imagee37.htm");
  this.fNewFile("Undo  ","imagee38.htm");
  this.fNewFile("Vertical Flip  ","imagee39.htm");
  this.fNewFile("Zoom In  ","imagee40.htm");
  this.fNewFile("Zoom Out  ","imagee41.htm");
  this.fNewFile("Specifying Color Depth  ","imagee42.htm");
  this.fNewFile("Introduction to Tables  ","tables.htm");
  this.fNewFile("Creating a Table  ","tables2.htm");
  this.fNewFile("Deleting a Table  ","tables3.htm");
  this.fNewFile("Inserting a Table within a Table  ","tables4.htm");
  this.fNewFile("Table Dialog Boxes and Menus  ","dialogbo.htm");
  this.fNewFile("The Insert Table Menu  ","dialogb2.htm");
  this.fNewFile("The Table Properties Dialog Box  ","dialogb3.htm");
  this.fNewFile("The Cell Properties Dialog Box  ","dialogb4.htm");
  this.fNewFile("The Table Context Sensitive Menu  ","dialogb5.htm");
  this.fNewFile("Manipulating Your Table's Format  ","manipula.htm");
  this.fNewFile("Choosing the Number of Rows and Columns  ","manipul2.htm");
  this.fNewFile("Specifying Table Width  ","manipul3.htm");
  this.fNewFile("Specifying Table Width by Percentage  ","manipul4.htm");
  this.fNewFile("Specifying Table Width by Pixels  ","manipul5.htm");
  this.fNewFile("Specifying Horizontal Alignment  ","manipul6.htm");
  this.fNewFile("Table Backgrounds  ","manipul7.htm");
  this.fNewFile("Specifying a Table's Background Color  ","manipul8.htm");
  this.fNewFile("Specifying a Background Image for a Table  ","manipul9.htm");
  this.fNewFile("Setting Table Borders  ","manipu10.htm");
  this.fNewFile("Assigning Border Color   ","manipu11.htm");
  this.fNewFile("Assigning Border Size  ","manipu12.htm");
  this.fNewFile("Working with Table Cells  ","cellprop.htm");
  this.fNewFile("Specifying the Width of a Cell  ","cellpro2.htm");
  this.fNewFile("Inserting a Cell  ","cellpro3.htm");
  this.fNewFile("Deleting a Cell  ","cellpro4.htm");
  this.fNewFile("Setting a Cell's Border Color  ","cellpro5.htm");
  this.fNewFile("Specifying a Cell's Background Color   ","cellpro6.htm");
  this.fNewFile("Specifying a Background Image for a Cell  ","cellpro7.htm");
  this.fNewFile("Using the Color Box  ","cellpro8.htm");
  this.fNewFile("Spanning Rows or Columns  ","cellpro9.htm");
  this.fNewFile("Spanning More than One Row or Column  ","cellpr10.htm");
  this.fNewFile("Aligning Text Within a Cell  ","cellpr11.htm");
  this.fNewFile("Setting Horizontal Alignment  ","cellpr12.htm");
  this.fNewFile("Setting Vertical Alignment  ","cellpr13.htm");
  this.fNewFile("Splitting a Cell  ","cellpr14.htm");
  this.fNewFile("Merging Two Cells  ","cellpr15.htm");
  this.fNewFile("Word Wrap  ","cellpr16.htm");
  this.fNewFile("Setting Cell Padding and Spacing  ","cellpr17.htm");
  this.fNewFile("Using Bookmarks  ","bookmara.htm");
  this.fNewFile("Creating a Bookmark  ","bookmar2.htm");
  this.fNewFile("Changing the Destination Window  ","bookmar3.htm");
  this.fNewFile("Using Hyperlinks  ","hyperlib.htm");
  this.fNewFile("Creating a Hyperlink  ","hyperli2.htm");
  this.fNewFile("Using a Quick Link  ","hyperli3.htm");
  this.fNewFile("Entering a Hyperlink Manually  ","hyperli4.htm");
  this.fNewFile("Testing a Hyperlink  ","hyperli5.htm");
  this.fNewFile("Creating a Hyperlink to a Location Within a Web Page  ","hyperli6.htm");
  this.fNewFile("Editing a Hyperlink  ","hyperli7.htm");
  this.fNewFile("Removing a Hyperlink  ","hyperli8.htm");
  this.fNewFile("Preventing a URL from Becoming a Hyperlink  ","hyperli9.htm");
  this.fNewFile("Working with HTML  ","html.htm");
  this.fNewFile("Viewing and Editing HTML  ","html2.htm");
  this.fNewFile("Editing a Section of a Page   ","html3.htm");
  this.fNewFile("Inserting HTML  ","html4.htm");
  this.fNewFile("Cleaning HTML  ","html5.htm");
  this.fNewFile("Inserting Content from MS Office 2000  ","html6.htm");
  this.fNewFile("Section 508 Compliance  ","508.htm");
  this.fNewFile("Moving the Cursor into eWebEditPro  ","5082.htm");
  this.fNewFile("Using eWebEditPro without a Mouse  ","5083.htm");
  this.fNewFile("Section 508 Tables  ","5084.htm");
}
