function  Book_AddIndexEntries(ParamIndex)
{
  ParamIndex.fSetTotalEntries(256);

  ParamIndex.fAddEntry("508 compliance\u00a0", new Array("508.htm#427149"));
  ParamIndex.fAddEntry("about eWebEditPro box\u00a0", new Array("tableof4.htm#452070"));
  ParamIndex.fAddEntry("absolute positioning of objects\u00a0", new Array("tableof5.htm#462155"));
  ParamIndex.fAddEntry("alignment	cell\u00a0", new Array("cellpr11.htm#441828"));
  ParamIndex.fAddEntry("alignment	image\u00a0", new Array("picture9.htm#439216"));
  ParamIndex.fAddEntry("alignment	table\u00a0", new Array("manipul6.htm#442369"));
  ParamIndex.fAddEntry("alignment	text\u00a0", new Array("tableof4.htm#452052"));
  ParamIndex.fAddEntry("alignment", new Array());
  ParamIndex.fAddEntry("background color	applying to text\u00a0", new Array("tableof4.htm#454975"));
  ParamIndex.fAddEntry("background color	cell	applying\u00a0", new Array("cellpro6.htm#441705"));
  ParamIndex.fAddEntry("background color	cell	deleting\u00a0", new Array("cellpro6.htm#451570"));
  ParamIndex.fAddEntry("background color	cell", new Array());
  ParamIndex.fAddEntry("background color	removing from text\u00a0", new Array("tableof4.htm#454975"));
  ParamIndex.fAddEntry("background color	table	applying\u00a0", new Array("manipul8.htm#447761"));
  ParamIndex.fAddEntry("background color	table	deleting\u00a0", new Array("manipul8.htm#439675"));
  ParamIndex.fAddEntry("background color	table", new Array());
  ParamIndex.fAddEntry("background color", new Array());
  ParamIndex.fAddEntry("background image	cell	deleting\u00a0", new Array("cellpro7.htm#450720"));
  ParamIndex.fAddEntry("background image	cell	inserting\u00a0", new Array("cellpro7.htm#450699"));
  ParamIndex.fAddEntry("background image	cell", new Array());
  ParamIndex.fAddEntry("background image	table	deleting\u00a0", new Array("manipul9.htm#446221"));
  ParamIndex.fAddEntry("background image	table	inserting\u00a0", new Array("manipul9.htm#446201"));
  ParamIndex.fAddEntry("background image	table", new Array());
  ParamIndex.fAddEntry("background image", new Array());
  ParamIndex.fAddEntry("bidirectional editing\u00a0", new Array("tableof6.htm#457345"));
  ParamIndex.fAddEntry("blur, WebImageFX command\u00a0", new Array("imageed5.htm#442082"));
  ParamIndex.fAddEntry("bold	toolbar option\u00a0", new Array("tableof4.htm#440901"));
  ParamIndex.fAddEntry("bold", new Array());
  ParamIndex.fAddEntry("bookmarks\u00a0", new Array("bookmara.htm#427149"));
  ParamIndex.fAddEntry("border	image	color\u00a0", new Array("picture8.htm#439237"));
  ParamIndex.fAddEntry("border	image	thickness\u00a0", new Array("picture8.htm#456386"));
  ParamIndex.fAddEntry("border	image", new Array());
  ParamIndex.fAddEntry("border", new Array());
  ParamIndex.fAddEntry("border color	cell\u00a0", new Array("cellpro5.htm#452310"));
  ParamIndex.fAddEntry("border color	table\u00a0", new Array("manipu11.htm#444589"));
  ParamIndex.fAddEntry("border color", new Array());
  ParamIndex.fAddEntry("border size	cell\u00a0", new Array("cellprop.htm#442659"));
  ParamIndex.fAddEntry("border size	table\u00a0", new Array("manipu12.htm#439806"));
  ParamIndex.fAddEntry("border size", new Array());
  ParamIndex.fAddEntry("brightness, WebImageFX command\u00a0", new Array("imageed6.htm#444845"));
  ParamIndex.fAddEntry("bullet	toolbar option\u00a0", new Array("tableof4.htm#452014"));
  ParamIndex.fAddEntry("bullet", new Array());
  ParamIndex.fAddEntry("buttons	adding to menu\u00a0", new Array("customi3.htm#451788"));
  ParamIndex.fAddEntry("buttons	rearranging on a menu\u00a0", new Array("customi3.htm#451814"));
  ParamIndex.fAddEntry("buttons	removing from menu\u00a0", new Array("customi3.htm#451788"));
  ParamIndex.fAddEntry("buttons", new Array());
  ParamIndex.fAddEntry("cells	background color\u00a0", new Array("cellpro6.htm#441705"));
  ParamIndex.fAddEntry("cells	background image	deleting\u00a0", new Array("cellpro7.htm#450720"));
  ParamIndex.fAddEntry("cells	background image	inserting\u00a0", new Array("cellpro7.htm#450699"));
  ParamIndex.fAddEntry("cells	background image", new Array());
  ParamIndex.fAddEntry("cells	border	color\u00a0", new Array("cellpro5.htm#452310"));
  ParamIndex.fAddEntry("cells	border	invisible\u00a0", new Array("cellpro5.htm#441623"));
  ParamIndex.fAddEntry("cells	border", new Array());
  ParamIndex.fAddEntry("cells	deleting\u00a0", new Array("cellpro4.htm#452377"));
  ParamIndex.fAddEntry("cells	inserting\u00a0", new Array("cellpro3.htm#452245"));
  ParamIndex.fAddEntry("cells	merging\u00a0", new Array("cellpr15.htm#442257"));
  ParamIndex.fAddEntry("cells	padding\u00a0", new Array("cellpr17.htm#442832"));
  ParamIndex.fAddEntry("cells	spacing\u00a0", new Array("cellpr17.htm#442832"));
  ParamIndex.fAddEntry("cells	splitting\u00a0", new Array("cellpr14.htm#441931"));
  ParamIndex.fAddEntry("cells	text alignment\u00a0", new Array("cellpr11.htm#441828"));
  ParamIndex.fAddEntry("cells	width\u00a0", new Array("cellpro2.htm#442591"));
  ParamIndex.fAddEntry("cells", new Array());
  ParamIndex.fAddEntry("choose color, WebImageFX command\u00a0", new Array("imageed7.htm#487602"));
  ParamIndex.fAddEntry("choose font, WebImageFX command\u00a0", new Array("imageed8.htm#487617"));
  ParamIndex.fAddEntry("cleaning HTML\u00a0", new Array("html5.htm#440340"));
  ParamIndex.fAddEntry("color	background	cell	applying\u00a0", new Array("cellpro6.htm#441705"));
  ParamIndex.fAddEntry("color	background	cell	deleting\u00a0", new Array("cellpro6.htm#451570"));
  ParamIndex.fAddEntry("color	background	cell", new Array());
  ParamIndex.fAddEntry("color	background	table	applying\u00a0", new Array("manipul8.htm#447761"));
  ParamIndex.fAddEntry("color	background	table	deleting\u00a0", new Array("manipul8.htm#439675"));
  ParamIndex.fAddEntry("color	background	table", new Array());
  ParamIndex.fAddEntry("color	background", new Array());
  ParamIndex.fAddEntry("color	cell border\u00a0	default\u00a0", new Array("dialogb4.htm#443189"));
  ParamIndex.fAddEntry("color	cell border\u00a0", new Array("cellpro5.htm#452310"));
  ParamIndex.fAddEntry("color	font, changing\u00a0", new Array("tableof4.htm#452341"));
  ParamIndex.fAddEntry("color	picture border\u00a0", new Array("picture8.htm#439237"));
  ParamIndex.fAddEntry("color	table border\u00a0	default\u00a0", new Array("dialogb3.htm#443299"));
  ParamIndex.fAddEntry("color	table border\u00a0", new Array("manipu11.htm#444589"));
  ParamIndex.fAddEntry("color", new Array());
  ParamIndex.fAddEntry("color depth, specifying\u00a0", new Array("imagee42.htm#442494"));
  ParamIndex.fAddEntry("color depth, WebImageFX command\u00a0", new Array("imageed9.htm#487571"));
  ParamIndex.fAddEntry("columns	table	adding\u00a0", new Array("manipul2.htm#439025"));
  ParamIndex.fAddEntry("columns	table	deleting\u00a0", new Array("manipul2.htm#439025"));
  ParamIndex.fAddEntry("columns	table	spanning\u00a0", new Array("cellpro9.htm#441701"));
  ParamIndex.fAddEntry("columns	table	specifying\u00a0", new Array("manipul2.htm#439012"));
  ParamIndex.fAddEntry("columns	table", new Array());
  ParamIndex.fAddEntry("columns", new Array());
  ParamIndex.fAddEntry("contrast, WebImageFX command\u00a0", new Array("imagee10.htm#445281"));
  ParamIndex.fAddEntry("copy	toolbar and menu option\u00a0", new Array("tableof4.htm#440807"));
  ParamIndex.fAddEntry("copy", new Array());
  ParamIndex.fAddEntry("copy, WebImageFX command\u00a0", new Array("imagee11.htm#445550"));
  ParamIndex.fAddEntry("copying information from other applications\u00a0", new Array("copya.htm#427149"));
  ParamIndex.fAddEntry("copyright character, inserting\u00a0", new Array("tableof4.htm#452202"));
  ParamIndex.fAddEntry("create new, WebImageFX command\u00a0", new Array("imagee12.htm#459967"));
  ParamIndex.fAddEntry("crop, WebImageFX command\u00a0", new Array("imagee13.htm#459932"));
  ParamIndex.fAddEntry("customizing toolbar\u00a0", new Array("customiz.htm#454988"));
  ParamIndex.fAddEntry("cut, toolbar and menu option\u00a0", new Array("tableof4.htm#440795"));
  ParamIndex.fAddEntry("delete, WebImageFX command\u00a0", new Array("imagee14.htm#444519"));
  ParamIndex.fAddEntry("deleting	cell\u00a0", new Array("cellpro4.htm#452377"));
  ParamIndex.fAddEntry("deleting	table\u00a0", new Array("tables3.htm#440892"));
  ParamIndex.fAddEntry("deleting", new Array());
  ParamIndex.fAddEntry("dimensions, WebImageFX command\u00a0", new Array("imagee15.htm#446037"));
  ParamIndex.fAddEntry("editing HTML\u00a0", new Array("html3.htm#440352"));
  ParamIndex.fAddEntry("exit, WebImageFX command\u00a0", new Array("imagee16.htm#490282"));
  ParamIndex.fAddEntry("finding text\u00a0", new Array("finda.htm#427149"));
  ParamIndex.fAddEntry("fonts	background color\u00a0", new Array("tableof4.htm#454975"));
  ParamIndex.fAddEntry("fonts	color\u00a0", new Array("tableof4.htm#452336"));
  ParamIndex.fAddEntry("fonts	heading size\u00a0", new Array("tableof4.htm#452268"));
  ParamIndex.fAddEntry("fonts	size\u00a0", new Array("tableof4.htm#440891"));
  ParamIndex.fAddEntry("fonts	style\u00a0", new Array("tableof4.htm#440881"));
  ParamIndex.fAddEntry("fonts", new Array());
  ParamIndex.fAddEntry("form elements toolbar\u00a0", new Array("tableof7.htm#458399"));
  ParamIndex.fAddEntry("forms	replacing form or element information\u00a0", new Array("tableof7.htm#461350"));
  ParamIndex.fAddEntry("forms	updating form or element information\u00a0", new Array("tableof7.htm#461390"));
  ParamIndex.fAddEntry("forms", new Array());
  ParamIndex.fAddEntry("freehand, WebImageFX command\u00a0", new Array("imagee17.htm#495876"));
  ParamIndex.fAddEntry("horizontal flip, WebImageFX command\u00a0", new Array("imagee18.htm#471283"));
  ParamIndex.fAddEntry("horizontal line, inserting\u00a0", new Array("tableof4.htm#447030"));
  ParamIndex.fAddEntry("HTML	cleaning\u00a0", new Array("html5.htm#440340"));
  ParamIndex.fAddEntry("HTML	editing\u00a0", new Array("html3.htm#440352"));
  ParamIndex.fAddEntry("HTML	inserting\u00a0", new Array("html4.htm#439143"));
  ParamIndex.fAddEntry("HTML	viewing\u00a0", new Array("html2.htm#443493"));
  ParamIndex.fAddEntry("HTML", new Array());
  ParamIndex.fAddEntry("hyperlinks\u00a0	creating\u00a0", new Array("hyperli2.htm#442923"));
  ParamIndex.fAddEntry("hyperlinks\u00a0	editing\u00a0", new Array("hyperli7.htm#440076"));
  ParamIndex.fAddEntry("hyperlinks\u00a0	entering manually\u00a0", new Array("hyperli4.htm#441842"));
  ParamIndex.fAddEntry("hyperlinks\u00a0	preventing\u00a0", new Array("hyperli9.htm#439904"));
  ParamIndex.fAddEntry("hyperlinks\u00a0	removing\u00a0", new Array("hyperli8.htm#442208"));
  ParamIndex.fAddEntry("hyperlinks\u00a0	testing\u00a0", new Array("hyperli5.htm#439780"));
  ParamIndex.fAddEntry("hyperlinks\u00a0	to a bookmark in another web page\u00a0", new Array("hyperli6.htm#440015"));
  ParamIndex.fAddEntry("hyperlinks\u00a0	using a Quick Link\u00a0", new Array("hyperli3.htm#441629"));
  ParamIndex.fAddEntry("hyperlinks\u00a0", new Array("hyperlib.htm#427149"));
  ParamIndex.fAddEntry("image info, WebImageFX command\u00a0", new Array("imagee19.htm#448674"));
  ParamIndex.fAddEntry("image upload	from Microsoft Word document\u00a0", new Array("msword2.htm#441969"));
  ParamIndex.fAddEntry("image upload	inserting picture from computer\u00a0", new Array("picture4.htm#445339"));
  ParamIndex.fAddEntry("image upload	media file selection\u00a0", new Array("picture2.htm#452096"));
  ParamIndex.fAddEntry("image upload", new Array());
  ParamIndex.fAddEntry("images	adding space around\u00a0", new Array("pictur11.htm#447456"));
  ParamIndex.fAddEntry("images	aligning\u00a0", new Array("picture9.htm#439216"));
  ParamIndex.fAddEntry("images	background	cell, inserting\u00a0", new Array("cellpro7.htm#450699"));
  ParamIndex.fAddEntry("images	background	table, inserting\u00a0", new Array("manipul9.htm#446201"));
  ParamIndex.fAddEntry("images	background", new Array());
  ParamIndex.fAddEntry("images	border	color\u00a0", new Array("picture8.htm#439237"));
  ParamIndex.fAddEntry("images	border	thickness\u00a0", new Array("picture8.htm#456386"));
  ParamIndex.fAddEntry("images	border", new Array());
  ParamIndex.fAddEntry("images	deleting\u00a0", new Array("pictur15.htm#463783"));
  ParamIndex.fAddEntry("images	deleting from server\u00a0", new Array("picture3.htm#454261"));
  ParamIndex.fAddEntry("images	editing\u00a0", new Array("imageedi.htm#438886"));
  ParamIndex.fAddEntry("images	inserting\u00a0", new Array("pictures.htm#454379"));
  ParamIndex.fAddEntry("images	inserting from server into editor\u00a0", new Array("picture3.htm#455410"));
  ParamIndex.fAddEntry("images	inserting from your computer\u00a0", new Array("picture4.htm#445339"));
  ParamIndex.fAddEntry("images	locking in position\u00a0", new Array("tableof5.htm#457403"));
  ParamIndex.fAddEntry("images	moving to server\u00a0", new Array("pictur14.htm#463717"));
  ParamIndex.fAddEntry("images	scanning\u00a0", new Array("imagee36.htm#465748"));
  ParamIndex.fAddEntry("images	specifying color depth\u00a0", new Array("imagee42.htm#442494"));
  ParamIndex.fAddEntry("images", new Array());
  ParamIndex.fAddEntry("indent	toolbar option\u00a0", new Array("tableof4.htm#452033"));
  ParamIndex.fAddEntry("indent", new Array());
  ParamIndex.fAddEntry("insert table	toolbar button\u00a0", new Array("dialogb2.htm#444338"));
  ParamIndex.fAddEntry("insert table", new Array());
  ParamIndex.fAddEntry("inserting	cells\u00a0", new Array("cellpro3.htm#452245"));
  ParamIndex.fAddEntry("inserting	HTML\u00a0", new Array("html4.htm#439143"));
  ParamIndex.fAddEntry("inserting", new Array());
  ParamIndex.fAddEntry("Internet addresses, spell checking\u00a0", new Array("spellch6.htm#442031"));
  ParamIndex.fAddEntry("italic	toolbar option\u00a0", new Array("tableof4.htm#440912"));
  ParamIndex.fAddEntry("italic", new Array());
  ParamIndex.fAddEntry("jumps, see bookmarks and hyperlinks", new Array("bookmar2.htm#442361"));
  ParamIndex.fAddEntry("justify	toolbar option\u00a0", new Array("tableof4.htm#452052"));
  ParamIndex.fAddEntry("justify", new Array());
  ParamIndex.fAddEntry("license keys, viewing\u00a0", new Array("tableof4.htm#452070"));
  ParamIndex.fAddEntry("line, WebImageFX command\u00a0", new Array("imagee20.htm#472721"));
  ParamIndex.fAddEntry("lock table or image in position\u00a0", new Array("tableof5.htm#457403"));
  ParamIndex.fAddEntry("menus	adding to toolbar\u00a0", new Array("customi2.htm#443554"));
  ParamIndex.fAddEntry("menus	changing orientation\u00a0", new Array("customi8.htm#445711"));
  ParamIndex.fAddEntry("menus	creating\u00a0", new Array("customi6.htm#445246"));
  ParamIndex.fAddEntry("menus	moving from toolbar\u00a0", new Array("customi7.htm#445504"));
  ParamIndex.fAddEntry("menus	rearranging on toolbar\u00a0", new Array("customi5.htm#444545"));
  ParamIndex.fAddEntry("menus	removing from toolbar\u00a0", new Array("customi2.htm#443554"));
  ParamIndex.fAddEntry("menus", new Array());
  ParamIndex.fAddEntry("merging cells\u00a0", new Array("cellpr15.htm#442257"));
  ParamIndex.fAddEntry("Microsoft Word	editing in\u00a0", new Array("msworda.htm#440736"));
  ParamIndex.fAddEntry("Microsoft Word	editing XML documents\u00a0", new Array("msword3.htm#442004"));
  ParamIndex.fAddEntry("Microsoft Word	uploading image from\u00a0", new Array("msword2.htm#441969"));
  ParamIndex.fAddEntry("Microsoft Word", new Array());
  ParamIndex.fAddEntry("number	toolbar option\u00a0", new Array("tableof4.htm#451999"));
  ParamIndex.fAddEntry("number", new Array());
  ParamIndex.fAddEntry("numbers in words, spell checking\u00a0", new Array("spellch6.htm#442031"));
  ParamIndex.fAddEntry("objects, absolute positioning\u00a0", new Array("tableof5.htm#462155"));
  ParamIndex.fAddEntry("Office 2000, inserting content from\u00a0", new Array("html6.htm#443325"));
  ParamIndex.fAddEntry("open, WebImageFX command\u00a0", new Array("imagee21.htm#460773"));
  ParamIndex.fAddEntry("oval, WebImageFX command\u00a0", new Array("imagee22.htm#474154"));
  ParamIndex.fAddEntry("padding, cell\u00a0", new Array("cellpr17.htm#442832"));
  ParamIndex.fAddEntry("paste	toolbar and menu option\u00a0", new Array("tableof4.htm#440819"));
  ParamIndex.fAddEntry("paste", new Array());
  ParamIndex.fAddEntry("paste as new image, WebImageFX command\u00a0", new Array("imagee23.htm#487358"));
  ParamIndex.fAddEntry("paste text	toolbar and menu option\u00a0", new Array("tableof4.htm#460742"));
  ParamIndex.fAddEntry("paste text", new Array());
  ParamIndex.fAddEntry("picture properties	image upload\u00a0", new Array("picture2.htm#452096"));
  ParamIndex.fAddEntry("picture properties", new Array());
  ParamIndex.fAddEntry("pictures	inserting see image upload", new Array("picture2.htm#452096"));
  ParamIndex.fAddEntry("pictures", new Array());
  ParamIndex.fAddEntry("pixels\u00a0", new Array("picture7.htm#439005"));
  ParamIndex.fAddEntry("pointer selection, WebImageFX command\u00a0", new Array("imagee24.htm#494248"));
  ParamIndex.fAddEntry("polygon, WebImageFX command\u00a0", new Array("imagee25.htm#474534"));
  ParamIndex.fAddEntry("position objects menu\u00a0", new Array("tableof5.htm#462155"));
  ParamIndex.fAddEntry("print editor content\u00a0", new Array("tableof4.htm#454951"));
  ParamIndex.fAddEntry("quick link\u00a0", new Array("hyperli3.htm#441629"));
  ParamIndex.fAddEntry("rectangle, WebImageFX command\u00a0", new Array("imagee26.htm#476812"));
  ParamIndex.fAddEntry("redisplay toolbars\u00a0", new Array("customi4.htm#451774"));
  ParamIndex.fAddEntry("redo, WebImageFX command\u00a0", new Array("imagee27.htm#475492"));
  ParamIndex.fAddEntry("registered trademark character, inserting\u00a0", new Array("tableof4.htm#452190"));
  ParamIndex.fAddEntry("replacing text\u00a0", new Array("finda.htm#427149"));
  ParamIndex.fAddEntry("right to left editing\u00a0", new Array("tableof6.htm#457345"));
  ParamIndex.fAddEntry("rotate, WebImageFX command\u00a0", new Array("imagee29.htm#444461"));
  ParamIndex.fAddEntry("rows	table	adding\u00a0", new Array("manipul2.htm#439025"));
  ParamIndex.fAddEntry("rows	table	deleting\u00a0", new Array("manipul2.htm#439025"));
  ParamIndex.fAddEntry("rows	table	spanning\u00a0", new Array("cellpro9.htm#441701"));
  ParamIndex.fAddEntry("rows	table	specifying\u00a0", new Array("manipul2.htm#439012"));
  ParamIndex.fAddEntry("rows	table", new Array());
  ParamIndex.fAddEntry("rows", new Array());
  ParamIndex.fAddEntry("save as, WebImageFX command\u00a0", new Array("imagee31.htm#461504"));
  ParamIndex.fAddEntry("save, WebImageFX command\u00a0", new Array("imagee30.htm#478527"));
  ParamIndex.fAddEntry("scanning an image\u00a0", new Array("imagee36.htm#465748"));
  ParamIndex.fAddEntry("search\u00a0	considering case of search term\u00a0", new Array("find6.htm#440192"));
  ParamIndex.fAddEntry("search\u00a0	direction\u00a0", new Array("find5.htm#440169"));
  ParamIndex.fAddEntry("search\u00a0	whole word match\u00a0", new Array("find7.htm#440200"));
  ParamIndex.fAddEntry("search\u00a0", new Array("finda.htm#427149"));
  ParamIndex.fAddEntry("section 508	compliance\u00a0", new Array("508.htm#427149"));
  ParamIndex.fAddEntry("section 508	tables\u00a0", new Array("5084.htm#441116"));
  ParamIndex.fAddEntry("section 508", new Array());
  ParamIndex.fAddEntry("select all	menu option\u00a0", new Array("contexts.htm#440800"));
  ParamIndex.fAddEntry("select all", new Array());
  ParamIndex.fAddEntry("select, WebImageFX command\u00a0", new Array("imagee32.htm#461481"));
  ParamIndex.fAddEntry("selecting text\u00a0", new Array("tableof2.htm#454650"));
  ParamIndex.fAddEntry("server, moving picture to\u00a0", new Array("pictur14.htm#463717"));
  ParamIndex.fAddEntry("sharpen, WebImageFX command\u00a0", new Array("imagee33.htm#444567"));
  ParamIndex.fAddEntry("shortcuts, keyboard\u00a0", new Array("tableof4.htm#452806"));
  ParamIndex.fAddEntry("space character, inserting\u00a0", new Array("tableof4.htm#452211"));
  ParamIndex.fAddEntry("spacing, cell\u00a0", new Array("cellpr17.htm#442832"));
  ParamIndex.fAddEntry("spanning	table columns\u00a0", new Array("cellpro9.htm#441701"));
  ParamIndex.fAddEntry("spanning	table rows\u00a0", new Array("cellpro9.htm#441701"));
  ParamIndex.fAddEntry("spanning", new Array());
  ParamIndex.fAddEntry("special characters, inserting\u00a0", new Array("tableof4.htm#452166"));
  ParamIndex.fAddEntry("spelling	check a single word\u00a0", new Array("spellch5.htm#441446"));
  ParamIndex.fAddEntry("spelling	check as you type\u00a0", new Array("spellch3.htm#438917"));
  ParamIndex.fAddEntry("spelling	check on demand\u00a0", new Array("spellch4.htm#439023"));
  ParamIndex.fAddEntry("spelling	check selected text\u00a0", new Array("spellch5.htm#441446"));
  ParamIndex.fAddEntry("spelling	checking file addresses\u00a0", new Array("spellch6.htm#442031"));
  ParamIndex.fAddEntry("spelling	checking Internet addresses\u00a0", new Array("spellch6.htm#442031"));
  ParamIndex.fAddEntry("spelling	checking uppercase words\u00a0", new Array("spellch6.htm#442031"));
  ParamIndex.fAddEntry("spelling	checking words with numbers\u00a0", new Array("spellch6.htm#442031"));
  ParamIndex.fAddEntry("spelling	fix errors\u00a0", new Array("spellch3.htm#438931"));
  ParamIndex.fAddEntry("spelling", new Array());
  ParamIndex.fAddEntry("splitting a cell\u00a0", new Array("cellpr14.htm#441931"));
  ParamIndex.fAddEntry("style class	assigning to text\u00a0", new Array("tableof4.htm#452353"));
  ParamIndex.fAddEntry("style class", new Array());
  ParamIndex.fAddEntry("tables	alignment\u00a0", new Array("manipul6.htm#442369"));
  ParamIndex.fAddEntry("tables	background color	applying\u00a0", new Array("manipul8.htm#447761"));
  ParamIndex.fAddEntry("tables	background color	deleting\u00a0", new Array("manipul8.htm#439675"));
  ParamIndex.fAddEntry("tables	background color", new Array());
  ParamIndex.fAddEntry("tables	background image	deleting\u00a0", new Array("manipul9.htm#446221"));
  ParamIndex.fAddEntry("tables	background image	inserting\u00a0", new Array("manipul9.htm#446201"));
  ParamIndex.fAddEntry("tables	background image", new Array());
  ParamIndex.fAddEntry("tables	border	color\u00a0", new Array("manipu11.htm#444589"));
  ParamIndex.fAddEntry("tables	border	invisible\u00a0", new Array("manipu11.htm#441134"));
  ParamIndex.fAddEntry("tables	border	size\u00a0", new Array("manipu12.htm#439806"));
  ParamIndex.fAddEntry("tables	border", new Array());
  ParamIndex.fAddEntry("tables	columns	adding\u00a0", new Array("manipul2.htm#439025"));
  ParamIndex.fAddEntry("tables	columns	deleting\u00a0", new Array("manipul2.htm#439025"));
  ParamIndex.fAddEntry("tables	columns	spanning\u00a0", new Array("cellpro9.htm#441701"));
  ParamIndex.fAddEntry("tables	columns	specifying\u00a0", new Array("manipul2.htm#439012"));
  ParamIndex.fAddEntry("tables	columns", new Array());
  ParamIndex.fAddEntry("tables	creating\u00a0", new Array("tables2.htm#453322"));
  ParamIndex.fAddEntry("tables	deleting\u00a0", new Array("tables3.htm#440892"));
  ParamIndex.fAddEntry("tables	inserting within a table\u00a0", new Array("tables4.htm#439918"));
  ParamIndex.fAddEntry("tables	locking in position\u00a0", new Array("tableof5.htm#457403"));
  ParamIndex.fAddEntry("tables	rows	adding\u00a0", new Array("manipul2.htm#439025"));
  ParamIndex.fAddEntry("tables	rows	deleting\u00a0", new Array("manipul2.htm#439025"));
  ParamIndex.fAddEntry("tables	rows	spanning\u00a0", new Array("cellpro9.htm#441701"));
  ParamIndex.fAddEntry("tables	rows	specifying\u00a0", new Array("manipul2.htm#439012"));
  ParamIndex.fAddEntry("tables	rows", new Array());
  ParamIndex.fAddEntry("tables	section 508\u00a0", new Array("5084.htm#441116"));
  ParamIndex.fAddEntry("tables	width	setting by percentage\u00a0", new Array("manipul4.htm#439126"));
  ParamIndex.fAddEntry("tables	width	setting by pixels\u00a0", new Array("manipul5.htm#439144"));
  ParamIndex.fAddEntry("tables	width", new Array());
  ParamIndex.fAddEntry("tables", new Array());
  ParamIndex.fAddEntry("text	aligning\u00a0	in columns\u00a0", new Array("tables4.htm#441571"));
  ParamIndex.fAddEntry("text	aligning\u00a0	within a cell\u00a0", new Array("cellpr11.htm#441828"));
  ParamIndex.fAddEntry("text	aligning\u00a0", new Array("tableof4.htm#452052"));
  ParamIndex.fAddEntry("text	direction menu\u00a0", new Array("tableof6.htm#457345"));
  ParamIndex.fAddEntry("text	indenting\u00a0", new Array("tableof4.htm#452033"));
  ParamIndex.fAddEntry("text	remove formatting\u00a0", new Array("tableof4.htm#454991"));
  ParamIndex.fAddEntry("text	replacing\u00a0", new Array("finda.htm#427149"));
  ParamIndex.fAddEntry("text	searching\u00a0", new Array("finda.htm#427149"));
  ParamIndex.fAddEntry("text	selecting\u00a0", new Array("tableof2.htm#454650"));
  ParamIndex.fAddEntry("text	WebImageFX command\u00a0", new Array("imagee34.htm#465894"));
  ParamIndex.fAddEntry("text", new Array());
  ParamIndex.fAddEntry("thumbnail, WebImageFX command\u00a0", new Array("imagee35.htm#465767"));
  ParamIndex.fAddEntry("toolbars	buttons\u00a0", new Array("tableof4.htm#452806"));
  ParamIndex.fAddEntry("toolbars	customizing\u00a0", new Array("customiz.htm#454988"));
  ParamIndex.fAddEntry("toolbars	redisplay\u00a0", new Array("customi4.htm#451774"));
  ParamIndex.fAddEntry("toolbars	restore\u00a0", new Array("customi4.htm#451774"));
  ParamIndex.fAddEntry("toolbars", new Array());
  ParamIndex.fAddEntry("trademark character, inserting\u00a0", new Array("tableof4.htm#452190"));
  ParamIndex.fAddEntry("twain acquire, WebImageFX command\u00a0", new Array("imagee36.htm#465748"));
  ParamIndex.fAddEntry("twain source, WebImageFX command\u00a0", new Array("imagee37.htm#462320"));
  ParamIndex.fAddEntry("underline	toolbar option\u00a0", new Array("tableof4.htm#440923"));
  ParamIndex.fAddEntry("underline", new Array());
  ParamIndex.fAddEntry("undo	toolbar option\u00a0", new Array("tableof4.htm#440830"));
  ParamIndex.fAddEntry("undo	WebImageFX command\u00a0", new Array("imagee38.htm#462282"));
  ParamIndex.fAddEntry("undo", new Array());
  ParamIndex.fAddEntry("uppercase words, spell checking\u00a0", new Array("spellch6.htm#442031"));
  ParamIndex.fAddEntry("version number, viewing\u00a0", new Array("tableof4.htm#452070"));
  ParamIndex.fAddEntry("vertical flip, WebImageFX command\u00a0", new Array("imagee39.htm#495992"));
  ParamIndex.fAddEntry("viewing HTML\u00a0", new Array("html2.htm#443493"));
  ParamIndex.fAddEntry("WebImageFX	assigning new name to image\u00a0", new Array("imageed3.htm#495489"));
  ParamIndex.fAddEntry("WebImageFX	choosing image\u00a0", new Array("imageed2.htm#479933"));
  ParamIndex.fAddEntry("WebImageFX	commands	blur\u00a0", new Array("imageed5.htm#442082"));
  ParamIndex.fAddEntry("WebImageFX	commands	brightness\u00a0", new Array("imageed6.htm#444845"));
  ParamIndex.fAddEntry("WebImageFX	commands	choose color\u00a0", new Array("imageed7.htm#487602"));
  ParamIndex.fAddEntry("WebImageFX	commands	choose font\u00a0", new Array("imageed8.htm#487617"));
  ParamIndex.fAddEntry("WebImageFX	commands	color depth\u00a0", new Array("imageed9.htm#487571"));
  ParamIndex.fAddEntry("WebImageFX	commands	contrast\u00a0", new Array("imagee10.htm#445281"));
  ParamIndex.fAddEntry("WebImageFX	commands	copy\u00a0", new Array("imagee11.htm#445550"));
  ParamIndex.fAddEntry("WebImageFX	commands	create new\u00a0", new Array("imagee12.htm#459967"));
  ParamIndex.fAddEntry("WebImageFX	commands	crop\u00a0", new Array("imagee13.htm#459932"));
  ParamIndex.fAddEntry("WebImageFX	commands	delete\u00a0", new Array("imagee14.htm#444519"));
  ParamIndex.fAddEntry("WebImageFX	commands	dimensions\u00a0", new Array("imagee15.htm#446037"));
  ParamIndex.fAddEntry("WebImageFX	commands	exit\u00a0", new Array("imagee16.htm#490282"));
  ParamIndex.fAddEntry("WebImageFX	commands	freehand\u00a0", new Array("imagee17.htm#495876"));
  ParamIndex.fAddEntry("WebImageFX	commands	horizontal flip\u00a0", new Array("imagee18.htm#471283"));
  ParamIndex.fAddEntry("WebImageFX	commands	image info\u00a0", new Array("imagee19.htm#448674"));
  ParamIndex.fAddEntry("WebImageFX	commands	line\u00a0", new Array("imagee20.htm#472721"));
  ParamIndex.fAddEntry("WebImageFX	commands	open\u00a0", new Array("imagee21.htm#460773"));
  ParamIndex.fAddEntry("WebImageFX	commands	oval\u00a0", new Array("imagee22.htm#474154"));
  ParamIndex.fAddEntry("WebImageFX	commands	paste as new image\u00a0", new Array("imagee23.htm#487358"));
  ParamIndex.fAddEntry("WebImageFX	commands	pointer selection\u00a0", new Array("imagee24.htm#494248"));
  ParamIndex.fAddEntry("WebImageFX	commands	polygon\u00a0", new Array("imagee25.htm#474534"));
  ParamIndex.fAddEntry("WebImageFX	commands	rectangle\u00a0", new Array("imagee26.htm#476812"));
  ParamIndex.fAddEntry("WebImageFX	commands	redo\u00a0", new Array("imagee27.htm#475492"));
  ParamIndex.fAddEntry("WebImageFX	commands	rotate\u00a0", new Array("imagee29.htm#444461"));
  ParamIndex.fAddEntry("WebImageFX	commands	save\u00a0", new Array("imagee30.htm#478527"));
  ParamIndex.fAddEntry("WebImageFX	commands	save as\u00a0", new Array("imagee31.htm#461504"));
  ParamIndex.fAddEntry("WebImageFX	commands	select\u00a0", new Array("imagee32.htm#461481"));
  ParamIndex.fAddEntry("WebImageFX	commands	sharpen\u00a0", new Array("imagee33.htm#444567"));
  ParamIndex.fAddEntry("WebImageFX	commands	text\u00a0", new Array("imagee34.htm#465894"));
  ParamIndex.fAddEntry("WebImageFX	commands	thumbnail\u00a0", new Array("imagee35.htm#465767"));
  ParamIndex.fAddEntry("WebImageFX	commands	twain acquire\u00a0", new Array("imagee36.htm#465748"));
  ParamIndex.fAddEntry("WebImageFX	commands	twain source\u00a0", new Array("imagee37.htm#462320"));
  ParamIndex.fAddEntry("WebImageFX	commands	undo\u00a0", new Array("imagee38.htm#462282"));
  ParamIndex.fAddEntry("WebImageFX	commands	vertical flip\u00a0", new Array("imagee39.htm#495992"));
  ParamIndex.fAddEntry("WebImageFX	commands	zoom in\u00a0", new Array("imagee40.htm#446300"));
  ParamIndex.fAddEntry("WebImageFX	commands	zoom out\u00a0", new Array("imagee41.htm#444577"));
  ParamIndex.fAddEntry("WebImageFX	commands", new Array());
  ParamIndex.fAddEntry("WebImageFX	introduction\u00a0", new Array("imageedi.htm#438886"));
  ParamIndex.fAddEntry("WebImageFX	menu commands\u00a0", new Array("imageed4.htm#492167"));
  ParamIndex.fAddEntry("WebImageFX	saving image\u00a0", new Array("imageed3.htm#492154"));
  ParamIndex.fAddEntry("WebImageFX	specifying color depth\u00a0", new Array("imagee42.htm#442494"));
  ParamIndex.fAddEntry("WebImageFX	toolbar buttons\u00a0", new Array("imageed4.htm#492167"));
  ParamIndex.fAddEntry("WebImageFX", new Array());
  ParamIndex.fAddEntry("whole word match\u00a0", new Array("find7.htm#440200"));
  ParamIndex.fAddEntry("width, table	setting by percentage\u00a0", new Array("manipul4.htm#439126"));
  ParamIndex.fAddEntry("width, table	setting by pixels\u00a0", new Array("manipul5.htm#439144"));
  ParamIndex.fAddEntry("width, table", new Array());
  ParamIndex.fAddEntry("word wrap\u00a0", new Array("cellpr16.htm#442311"));
  ParamIndex.fAddEntry("Word, Microsoft	editing in\u00a0", new Array("msworda.htm#440736"));
  ParamIndex.fAddEntry("Word, Microsoft	editing XML documents\u00a0", new Array("msword3.htm#442004"));
  ParamIndex.fAddEntry("Word, Microsoft	inserting from\u00a0", new Array("html6.htm#443325"));
  ParamIndex.fAddEntry("Word, Microsoft	uploading image from\u00a0", new Array("msword2.htm#441969"));
  ParamIndex.fAddEntry("Word, Microsoft", new Array());
  ParamIndex.fAddEntry("WYSIWYG, view as\u00a0", new Array("tableof4.htm#447097"));
  ParamIndex.fAddEntry("zoom in, WebImageFX command\u00a0", new Array("imagee40.htm#446300"));
  ParamIndex.fAddEntry("zoom out, WebImageFX command\u00a0", new Array("imagee41.htm#444577"));
}
