var g_sEWEPProduct = "eWebEditPro";
var g_sSupportPage = "http://www.ektron.com/support/ewebeditpro_support.aspx";
var g_sReleaseNote = "http://www.ektron.com/support/ewebeditpro_support.aspx?id=1762";
var g_sWIFXReleaseNote = "http://www.ektron.com/developers/webimagefxkb.cfm?id=808";
var g_sWIFXPage = "http://www.ektron.com/webimagefx.aspx";
var g_sWCMPage = "http://www.ektron.com/web-content-management-solutions.aspx";
var g_sCMS300Page = "http://www.ektron.com/cms300.aspx";
var g_sCMS400Page = "http://www.ektron.com/cms400.aspx";
var g_sDMS400Page = "http://www.ektron.com/dms400.aspx";