/*
Script generated by Aqua Data Studio 4.7.2 on aug-19-2009 10:25:21 AM
Database: taaladvies
Schema: < All Schema >
Objects: TABLE
*/
CREATE TABLE dtaaladv.bts_tks ( 
	tks_id	INTEGER NOT NULL,
	waarde	CLOB,
	veld  	VARCHAR(20) 
	);
CREATE TABLE dtaaladv.bts_tlv ( 
	tlv_id	INTEGER NOT NULL,
	waarde	CLOB,
	veld  	VARCHAR(20) 
	);
CREATE TABLE dtaaladv.td_brn ( 
	brn_id        	SERIAL NOT NULL,
	tlv_id        	INTEGER,
	tks_id        	INTEGER,
	brn_vmd_db    	TEXT,
	brn_vmd_htm_db	TEXT,
	ctt_db        	TEXT,
	ctt_url_htm_db	TEXT,
	brn_vnt_ds    	VARCHAR(255) NOT NULL,
	pgn_nmr_tx    	VARCHAR(50) NOT NULL 
	);
CREATE TABLE dtaaladv.td_ctt ( 
	ctt_id        	SERIAL NOT NULL,
	tlv_id        	INTEGER,
	tks_id        	INTEGER,
	zgv_id        	INTEGER NOT NULL,
	tlv_spc_htm_db	TEXT,
	ctt_htm_db    	TEXT,
	ctt_url_htm_db	TEXT,
	ctt_db        	TEXT,
	ctt_ul        	VARCHAR(255) NOT NULL,
	ctt_vnt_ds    	VARCHAR(255) NOT NULL,
	spc_ds        	VARCHAR(255) NOT NULL 
	);
CREATE TABLE dtaaladv.td_frq_ozk ( 
	frq_ozk_id	SERIAL NOT NULL,
	tlv_id    	INTEGER,
	tks_id    	INTEGER,
	zgv_id    	INTEGER NOT NULL,
	frq_nf    	VARCHAR(50),
	frq_vnt_ds	VARCHAR(255) NOT NULL,
	frq_spc_ds	VARCHAR(255) NOT NULL 
	);
CREATE TABLE dtaaladv.td_nsg_ref ( 
	nsg_ref_id    	SERIAL NOT NULL,
	tlv_id        	INTEGER,
	tks_id        	INTEGER,
	nsw_id        	INTEGER,
	ctt_url_htm_db	TEXT,
	ctt_db        	TEXT,
	nsg_vnt_ds    	VARCHAR(255) NOT NULL,
	pgn_nmr_tx    	VARCHAR(50) NOT NULL 
	);
CREATE TABLE dtaaladv.td_ntt ( 
	ntt_id    	SERIAL NOT NULL,
	tlv_id    	INTEGER,
	tks_id    	INTEGER,
	tav_id    	INTEGER,
	ntt_db    	TEXT,
	ntt_dt    	DATE NOT NULL,
	ntt_htm_db	TEXT 
	);
CREATE TABLE dtaaladv.td_opr ( 
	orp_id        	SERIAL NOT NULL,
	dmn_id        	INTEGER,
	gmn_id        	INTEGER,
	mdm_id        	INTEGER NOT NULL,
	orp_sts_cd    	CHAR(2),
	drb_id        	INTEGER NOT NULL,
	hkm_id        	INTEGER,
	tav_id        	INTEGER,
	dgp_id        	INTEGER,
	adv_vzk_typ_cd	CHAR(1) NOT NULL,
	dln_dt        	DATE,
	orp_dt        	DATE,
	orr_gst_fg    	CHAR(1),
	orr_nm        	VARCHAR(50) NOT NULL,
	orr_vrn_nm    	VARCHAR(50) NOT NULL,
	orr_fnt_ds    	VARCHAR(50),
	orr_ads_tx    	VARCHAR(50),
	orr_hus_nr    	CHAR(5),
	orr_bus_nr    	CHAR(4),
	orr_tel_nr    	CHAR(25),
	orr_fax_nr    	CHAR(20),
	agh_fg        	BOOLEAN NOT NULL,
	orr_ea        	VARCHAR(255),
	orp_opm_db    	TEXT,
	opr_hkm_nr    	VARCHAR(150) NOT NULL,
	utl_org_nm    	VARCHAR(50),
	slt_fg        	BOOLEAN NOT NULL 
	);
CREATE TABLE dtaaladv.td_opr_opladen_tu ( 
	orp_id	INTEGER NOT NULL 
	);
CREATE TABLE dtaaladv.td_taalunie_xml ( 
	xml_id        	SERIAL NOT NULL,
	ophaaldatum   	DATETIME YEAR to SECOND NOT NULL,
	ophaalurl     	LVARCHAR NOT NULL,
	taalvragen_xml	CLOB NOT NULL,
	foutboodschap 	CLOB 
	);
CREATE TABLE dtaaladv.td_tav ( 
	tav_id    	SERIAL NOT NULL,
	dmn_id    	INTEGER,
	tav_usr_id	CHAR(8) NOT NULL,
	gst_fg    	BOOLEAN NOT NULL,
	atf_fg    	BOOLEAN NOT NULL,
	tav_nm    	VARCHAR(50) NOT NULL,
	tav_vrn_nm	VARCHAR(50) NOT NULL,
	tav_ea    	VARCHAR(255) 
	);
CREATE TABLE dtaaladv.td_tks ( 
	rvt_id        	INTEGER,
	tks_id        	SERIAL NOT NULL,
	adv_vzk_id    	INTEGER NOT NULL,
	hfd_ttl_ds    	CLOB,
	hfd_ttl_htm_db	TEXT 
	);
CREATE TABLE dtaaladv.td_tlv_awd ( 
	drb_dt        	DATE,
	tlv_her_db    	TEXT,
	tlv_her_htm_db	TEXT,
	rvt_id        	INTEGER,
	ttl_db        	CLOB,
	ttl_htm_db    	TEXT,
	tlv_id        	SERIAL NOT NULL,
	adv_vzk_id    	INTEGER NOT NULL,
	tlv_ds        	CLOB,
	tlv_spc_htm_db	TEXT,
	tlv_inf_db    	CLOB,
	tlv_inf_htm_db	TEXT,
	tlv_vgn_nr    	INTEGER NOT NULL,
	tlv_vrl_agh_fg	BOOLEAN NOT NULL,
	awd_krt_db    	CLOB,
	awd_krt_htm_db	TEXT,
	awd_tol_db    	CLOB,
	awd_tol_htm_db	TEXT,
	awd_bjz_db    	CLOB,
	awd_bjz_htm_db	TEXT,
	tlv_upd_fg    	SMALLINT 
	);
CREATE TABLE dtaaladv.td_tsb ( 
	tsb_id        	SERIAL NOT NULL,
	tks_id        	INTEGER NOT NULL,
	tsb_ttl_htm_db	TEXT,
	tsb_db        	CLOB,
	tsb_htm_db    	TEXT,
	tsb_vgn_nr    	INTEGER NOT NULL,
	tsb_ttl_ds    	CLOB 
	);
CREATE TABLE dtaaladv.td_www_sck ( 
	www_sck_id    	SERIAL NOT NULL,
	tks_id        	INTEGER,
	tlv_id        	INTEGER,
	tlt_db        	TEXT,
	omg_db        	VARCHAR(255),
	www_sck_ul    	VARCHAR(255) NOT NULL,
	www_sck_htm_db	TEXT 
	);
CREATE TABLE dtaaladv.tp_ctg_bgf ( 
	ctg_bgf_id	SERIAL NOT NULL,
	hfd_ds    	CHAR(50) NOT NULL,
	atf_fg    	BOOLEAN NOT NULL 
	);
CREATE TABLE dtaaladv.tp_dgp ( 
	dgp_id    	SERIAL NOT NULL,
	dgp_alg_id	INTEGER NOT NULL,
	atf_fg    	BOOLEAN NOT NULL,
	dgp_spc_tx	VARCHAR(100) NOT NULL 
	);
CREATE TABLE dtaaladv.tp_dgp_alg ( 
	dgp_alg_id	SERIAL NOT NULL,
	dmn_id    	INTEGER NOT NULL,
	atf_fg    	BOOLEAN NOT NULL,
	dgp_alg_ds	VARCHAR(80) NOT NULL 
	);
CREATE TABLE dtaaladv.tp_dmn ( 
	dmn_id	SERIAL NOT NULL,
	dmn_nm	CHAR(20) NOT NULL 
	);
CREATE TABLE dtaaladv.tp_gmn ( 
	gmn_id	SERIAL NOT NULL,
	lnd_cd	CHAR(3),
	pst_cd	CHAR(12) NOT NULL,
	gmn_ds	CHAR(100) NOT NULL 
	);
CREATE TABLE dtaaladv.tp_hkm ( 
	hkm_id	SERIAL NOT NULL,
	hkm_nm	CHAR(50) NOT NULL,
	atf_fg	BOOLEAN NOT NULL 
	);
CREATE TABLE dtaaladv.tp_lnd ( 
	lnd_cd	CHAR(3) NOT NULL,
	lnd_nm	CHAR(50) NOT NULL 
	);
CREATE TABLE dtaaladv.tp_mdm ( 
	mdm_id	SERIAL NOT NULL,
	mdm_ds	CHAR(30) NOT NULL,
	atf_fg	BOOLEAN NOT NULL 
	);
CREATE TABLE dtaaladv.tp_nsw ( 
	nsw_id            	SERIAL NOT NULL,
	ctg_bgf_id        	INTEGER NOT NULL,
	atf_fg            	BOOLEAN NOT NULL,
	nsw_lng_ttl_db    	TEXT,
	nsw_ttl_htm_db    	TEXT,
	nsw_ttl_lng_htm_db	TEXT,
	nsw_ttl_ds        	VARCHAR(255) NOT NULL 
	);
CREATE TABLE dtaaladv.tp_orp_sts ( 
	orp_sts_cd	CHAR(2) NOT NULL,
	orp_sts_ds	CHAR(100) NOT NULL,
	atf_fg    	BOOLEAN NOT NULL 
	);
CREATE TABLE dtaaladv.tp_rvt ( 
	rvt_id	SERIAL NOT NULL,
	rvt_ds	CHAR(50) NOT NULL,
	atf_fg	BOOLEAN NOT NULL 
	);
CREATE TABLE dtaaladv.tp_sbn ( 
	sbn_id        	SERIAL NOT NULL,
	atf_fg        	BOOLEAN NOT NULL,
	ihd_tx        	TEXT,
	ihd_htm_db    	TEXT,
	htk_tx        	TEXT,
	ond_rgl_tx    	TEXT,
	slg_tx        	TEXT,
	htk_htm_db    	TEXT,
	ond_rgl_htm_db	TEXT,
	slg_htm_db    	TEXT,
	sbn_ds        	VARCHAR(255) NOT NULL 
	);
CREATE TABLE dtaaladv.tp_tgr ( 
	tgr_id    	SERIAL NOT NULL,
	tgr_ds    	CHAR(30) NOT NULL,
	tgr_oms_tx	VARCHAR(255) NOT NULL 
	);
CREATE TABLE dtaaladv.tp_zgv ( 
	zgv_id	SERIAL NOT NULL,
	zgv_ds	CHAR(100) NOT NULL,
	atf_fg	BOOLEAN NOT NULL 
	);
CREATE TABLE dtaaladv.tr_ctr ( 
	ctr_id    	SERIAL NOT NULL,
	odr_ctr_id	INTEGER,
	ctr_ds    	VARCHAR(255) NOT NULL,
	ctr_nmr_tx	CHAR(25) NOT NULL,
	ctr_nmr_nr	INTEGER,
	atf_fg    	BOOLEAN NOT NULL 
	);
CREATE TABLE dtaaladv.tr_drb ( 
	drb_id	SERIAL NOT NULL,
	sbn_id	INTEGER,
	mdm_id	INTEGER NOT NULL,
	drb_dt	DATE NOT NULL 
	);
CREATE TABLE dtaaladv.tr_tav_tgr ( 
	tav_id	INTEGER NOT NULL,
	tgr_id	INTEGER NOT NULL 
	);
CREATE TABLE dtaaladv.tr_tks_ctr ( 
	tks_id	INTEGER NOT NULL,
	ctr_id	INTEGER NOT NULL 
	);
CREATE TABLE dtaaladv.tr_tlv_awd_ctr ( 
	tlv_id	INTEGER NOT NULL,
	ctr_id	INTEGER NOT NULL 
	);
CREATE TABLE dtaaladv.tr_tlv_awd_tks ( 
	tlv_id	INTEGER NOT NULL,
	tks_id	INTEGER NOT NULL 
	);

CREATE INDEX dtaaladv.ix_bts_tks
	ON dtaaladv.bts_tks(tks_id);
CREATE INDEX dtaaladv.ix_bts_tlv
	ON dtaaladv.bts_tlv(tlv_id);
CREATE UNIQUE INDEX dtaaladv.uix_td_brn
	ON dtaaladv.td_brn(brn_id);
CREATE INDEX dtaaladv.ix_td_ctt
	ON dtaaladv.td_ctt(zgv_id);
CREATE UNIQUE INDEX dtaaladv.uix_td_ctt
	ON dtaaladv.td_ctt(ctt_id);
CREATE UNIQUE INDEX dtaaladv.uix_td_frq_ozk
	ON dtaaladv.td_frq_ozk(frq_ozk_id);
CREATE INDEX dtaaladv.ix_td_frq_ozk
	ON dtaaladv.td_frq_ozk(zgv_id);
CREATE UNIQUE INDEX dtaaladv.uix_td_nsg_ref
	ON dtaaladv.td_nsg_ref(nsg_ref_id);
CREATE INDEX dtaaladv.ix_td_nsg_ref
	ON dtaaladv.td_nsg_ref(nsw_id);
CREATE INDEX dtaaladv.ix_td_ntt
	ON dtaaladv.td_ntt(tav_id);
CREATE UNIQUE INDEX dtaaladv.uix_td_ntt
	ON dtaaladv.td_ntt(ntt_id);
CREATE UNIQUE INDEX dtaaladv.uix_td_opr
	ON dtaaladv.td_opr(orp_id);
CREATE INDEX dtaaladv.ix_td_opr_05
	ON dtaaladv.td_opr(gmn_id);
CREATE INDEX dtaaladv.ix_td_opr_07
	ON dtaaladv.td_opr(mdm_id);
CREATE INDEX dtaaladv.ix_td_opr_02
	ON dtaaladv.td_opr(hkm_id);
CREATE INDEX dtaaladv.ix_td_opr_10
	ON dtaaladv.td_opr(dgp_id);
CREATE INDEX dtaaladv.ix_td_opr_04
	ON dtaaladv.td_opr(orp_sts_cd);
CREATE INDEX dtaaladv.ix_td_opr_09
	ON dtaaladv.td_opr(dmn_id);
CREATE INDEX dtaaladv.ix_td_opr_06
	ON dtaaladv.td_opr(tav_id);
CREATE INDEX dtaaladv.ix_td_opr_08
	ON dtaaladv.td_opr(drb_id);
CREATE INDEX dtaaladv.ix_td_opr_03
	ON dtaaladv.td_opr(orp_dt);
CREATE INDEX dtaaladv.ix_td_opr_01
	ON dtaaladv.td_opr(agh_fg);
CREATE UNIQUE INDEX dtaaladv. 136_112
	ON dtaaladv.td_opr_opladen_tu(orp_id);
CREATE UNIQUE INDEX dtaaladv.uix_td_taalunie_xml
	ON dtaaladv.td_taalunie_xml(ophaaldatum);
CREATE INDEX dtaaladv.ix_td_tav
	ON dtaaladv.td_tav(dmn_id);
CREATE UNIQUE INDEX dtaaladv.uix_td_tav
	ON dtaaladv.td_tav(tav_id);
CREATE INDEX dtaaladv.ix_td_tks_01
	ON dtaaladv.td_tks(adv_vzk_id);
CREATE INDEX dtaaladv.ix_td_tks_02
	ON dtaaladv.td_tks(rvt_id);
CREATE UNIQUE INDEX dtaaladv.uix_td_tks
	ON dtaaladv.td_tks(tks_id);
CREATE UNIQUE INDEX dtaaladv.uix_td_tlv_awd
	ON dtaaladv.td_tlv_awd(tlv_id);
CREATE INDEX dtaaladv.ix_td_tlv_awd_02
	ON dtaaladv.td_tlv_awd(tlv_vrl_agh_fg);
CREATE INDEX dtaaladv.ix_td_tlv_awd_01
	ON dtaaladv.td_tlv_awd(rvt_id);
CREATE INDEX dtaaladv.ix_td_tlv_awd_03
	ON dtaaladv.td_tlv_awd(adv_vzk_id);
CREATE UNIQUE INDEX dtaaladv.uix_td_tsb
	ON dtaaladv.td_tsb(tsb_id);
CREATE INDEX dtaaladv.ix_td_tsb
	ON dtaaladv.td_tsb(tks_id);
CREATE UNIQUE INDEX dtaaladv.uix_td_www_sck
	ON dtaaladv.td_www_sck(www_sck_id);
CREATE UNIQUE INDEX dtaaladv.uix_tp_ctg_bgf
	ON dtaaladv.tp_ctg_bgf(ctg_bgf_id);
CREATE INDEX dtaaladv.ix_tp_dgp
	ON dtaaladv.tp_dgp(dgp_alg_id);
CREATE UNIQUE INDEX dtaaladv.uix_tp_dgp
	ON dtaaladv.tp_dgp(dgp_id);
CREATE INDEX dtaaladv.ix_tp_dgp_alg
	ON dtaaladv.tp_dgp_alg(dmn_id);
CREATE UNIQUE INDEX dtaaladv.uix_tp_dgp_alg
	ON dtaaladv.tp_dgp_alg(dgp_alg_id);
CREATE UNIQUE INDEX dtaaladv.uix_tp_dmn
	ON dtaaladv.tp_dmn(dmn_id);
CREATE INDEX dtaaladv.ix_tp_gmn
	ON dtaaladv.tp_gmn(lnd_cd);
CREATE UNIQUE INDEX dtaaladv.uix_tp_gmn
	ON dtaaladv.tp_gmn(gmn_id);
CREATE UNIQUE INDEX dtaaladv.uix_tp_hkm
	ON dtaaladv.tp_hkm(hkm_id);
CREATE UNIQUE INDEX dtaaladv.uix_tp_lnd
	ON dtaaladv.tp_lnd(lnd_cd);
CREATE UNIQUE INDEX dtaaladv.uix_tp_mdm
	ON dtaaladv.tp_mdm(mdm_id);
CREATE INDEX dtaaladv.ix_tp_nsw
	ON dtaaladv.tp_nsw(ctg_bgf_id);
CREATE UNIQUE INDEX dtaaladv.uix_tp_nsw
	ON dtaaladv.tp_nsw(nsw_id);
CREATE UNIQUE INDEX dtaaladv.uix_tp_orp_sts
	ON dtaaladv.tp_orp_sts(orp_sts_cd);
CREATE UNIQUE INDEX dtaaladv.uix_tp_rvt
	ON dtaaladv.tp_rvt(rvt_id);
CREATE UNIQUE INDEX dtaaladv.uix_tp_sbn
	ON dtaaladv.tp_sbn(sbn_id);
CREATE UNIQUE INDEX dtaaladv.uix_tp_tgr
	ON dtaaladv.tp_tgr(tgr_id);
CREATE UNIQUE INDEX dtaaladv.uix_tp_zgv
	ON dtaaladv.tp_zgv(zgv_id);
CREATE UNIQUE INDEX dtaaladv.uix_tr_ctr
	ON dtaaladv.tr_ctr(ctr_id);
CREATE INDEX dtaaladv.ix_tr_ctr_01
	ON dtaaladv.tr_ctr(ctr_nmr_tx);
CREATE INDEX dtaaladv.ix_tr_ctr_02
	ON dtaaladv.tr_ctr(odr_ctr_id);
CREATE INDEX dtaaladv.ix_tr_drb_01
	ON dtaaladv.tr_drb(mdm_id);
CREATE UNIQUE INDEX dtaaladv.uix_tr_drb
	ON dtaaladv.tr_drb(drb_id);
CREATE INDEX dtaaladv.ix_tr_drb_02
	ON dtaaladv.tr_drb(sbn_id);
CREATE UNIQUE INDEX dtaaladv.uix_tr_tav_tgr_02
	ON dtaaladv.tr_tav_tgr(tav_id, tgr_id);
CREATE INDEX dtaaladv.ix_tr_tav_tgr_02
	ON dtaaladv.tr_tav_tgr(tav_id);
CREATE UNIQUE INDEX dtaaladv.uix_tr_tav_tgr_01
	ON dtaaladv.tr_tav_tgr(tav_id, tgr_id);
CREATE INDEX dtaaladv.ix_tr_tav_tgr_01
	ON dtaaladv.tr_tav_tgr(tgr_id);
CREATE INDEX dtaaladv.ix_tr_tks_ctr
	ON dtaaladv.tr_tks_ctr(ctr_id);
CREATE UNIQUE INDEX dtaaladv.uix_tr_tks_ctr_02
	ON dtaaladv.tr_tks_ctr(tks_id, ctr_id);
CREATE UNIQUE INDEX dtaaladv.uix_tr_tks_ctr_01
	ON dtaaladv.tr_tks_ctr(tks_id, ctr_id);
CREATE UNIQUE INDEX dtaaladv.uix_tr_tlv_awd_ctr_02
	ON dtaaladv.tr_tlv_awd_ctr(tlv_id, ctr_id);
CREATE INDEX dtaaladv.ix_tr_tlv_awd_ctr
	ON dtaaladv.tr_tlv_awd_ctr(ctr_id);
CREATE UNIQUE INDEX dtaaladv.uix_tr_tlv_awd_ctr_01
	ON dtaaladv.tr_tlv_awd_ctr(tlv_id, ctr_id);
CREATE UNIQUE INDEX dtaaladv.uix_tr_tlv_awd_tks_02
	ON dtaaladv.tr_tlv_awd_tks(tlv_id, tks_id);
CREATE UNIQUE INDEX dtaaladv.uix_tr_tlv_awd_tks_01
	ON dtaaladv.tr_tlv_awd_tks(tlv_id, tks_id);
ALTER TABLE dtaaladv.td_brn
	ADD CONSTRAINT ( PRIMARY KEY (brn_id) CONSTRAINT pk_td_brn );
ALTER TABLE dtaaladv.td_ctt
	ADD CONSTRAINT ( PRIMARY KEY (ctt_id) CONSTRAINT pk_td_ctt );
ALTER TABLE dtaaladv.td_frq_ozk
	ADD CONSTRAINT ( PRIMARY KEY (frq_ozk_id) CONSTRAINT pk_td_frq_ozk );
ALTER TABLE dtaaladv.td_nsg_ref
	ADD CONSTRAINT ( PRIMARY KEY (nsg_ref_id) CONSTRAINT pk_td_nsg_ref );
ALTER TABLE dtaaladv.td_ntt
	ADD CONSTRAINT ( PRIMARY KEY (ntt_id) CONSTRAINT pk_td_ntt );
ALTER TABLE dtaaladv.td_opr
	ADD CONSTRAINT ( PRIMARY KEY (orp_id) CONSTRAINT pk_td_opr );
ALTER TABLE dtaaladv.td_tav
	ADD CONSTRAINT ( PRIMARY KEY (tav_id) CONSTRAINT pk_td_tav );
ALTER TABLE dtaaladv.td_tks
	ADD CONSTRAINT ( PRIMARY KEY (tks_id) CONSTRAINT pk_td_tks );
ALTER TABLE dtaaladv.td_tlv_awd
	ADD CONSTRAINT ( PRIMARY KEY (tlv_id) CONSTRAINT pk_td_tlv );
ALTER TABLE dtaaladv.td_tsb
	ADD CONSTRAINT ( PRIMARY KEY (tsb_id) CONSTRAINT pk_td_tsb );
ALTER TABLE dtaaladv.td_www_sck
	ADD CONSTRAINT ( PRIMARY KEY (www_sck_id) CONSTRAINT pk_td_www_sck );
ALTER TABLE dtaaladv.tp_ctg_bgf
	ADD CONSTRAINT ( PRIMARY KEY (ctg_bgf_id) CONSTRAINT pk_tp_ctg_bgf );
ALTER TABLE dtaaladv.tp_dgp
	ADD CONSTRAINT ( PRIMARY KEY (dgp_id) CONSTRAINT pk_tp_dgp );
ALTER TABLE dtaaladv.tp_dgp_alg
	ADD CONSTRAINT ( PRIMARY KEY (dgp_alg_id) CONSTRAINT pk_tp_dgp_alg );
ALTER TABLE dtaaladv.tp_dmn
	ADD CONSTRAINT ( PRIMARY KEY (dmn_id) CONSTRAINT pk_tp_dmn );
ALTER TABLE dtaaladv.tp_gmn
	ADD CONSTRAINT ( PRIMARY KEY (gmn_id) CONSTRAINT pk_tp_gmn );
ALTER TABLE dtaaladv.tp_hkm
	ADD CONSTRAINT ( PRIMARY KEY (hkm_id) CONSTRAINT pk_tp_hkm );
ALTER TABLE dtaaladv.tp_lnd
	ADD CONSTRAINT ( PRIMARY KEY (lnd_cd) CONSTRAINT pk_tp_lnd );
ALTER TABLE dtaaladv.tp_mdm
	ADD CONSTRAINT ( PRIMARY KEY (mdm_id) CONSTRAINT pk_tp_mdm );
ALTER TABLE dtaaladv.tp_nsw
	ADD CONSTRAINT ( PRIMARY KEY (nsw_id) CONSTRAINT pk_tp_nsw );
ALTER TABLE dtaaladv.tp_orp_sts
	ADD CONSTRAINT ( PRIMARY KEY (orp_sts_cd) CONSTRAINT pk_tp_orp_sts );
ALTER TABLE dtaaladv.tp_rvt
	ADD CONSTRAINT ( PRIMARY KEY (rvt_id) CONSTRAINT pk_tp_rvt );
ALTER TABLE dtaaladv.tp_sbn
	ADD CONSTRAINT ( PRIMARY KEY (sbn_id) CONSTRAINT pk_tp_sbn );
ALTER TABLE dtaaladv.tp_tgr
	ADD CONSTRAINT ( PRIMARY KEY (tgr_id) CONSTRAINT pk_tp_tgr );
ALTER TABLE dtaaladv.tp_zgv
	ADD CONSTRAINT ( PRIMARY KEY (zgv_id) CONSTRAINT pk_tp_zgv );
ALTER TABLE dtaaladv.tr_ctr
	ADD CONSTRAINT ( PRIMARY KEY (ctr_id) CONSTRAINT pk_tr_ctr );
ALTER TABLE dtaaladv.tr_drb
	ADD CONSTRAINT ( PRIMARY KEY (drb_id) CONSTRAINT pk_tr_drb );
ALTER TABLE dtaaladv.tr_tav_tgr
	ADD CONSTRAINT ( PRIMARY KEY (tav_id, tgr_id) CONSTRAINT pk_tr_tav_tgr );
ALTER TABLE dtaaladv.tr_tks_ctr
	ADD CONSTRAINT ( PRIMARY KEY (ctr_id, tks_id) CONSTRAINT pk_tr_tks_ctr );
ALTER TABLE dtaaladv.tr_tlv_awd_ctr
	ADD CONSTRAINT ( PRIMARY KEY (ctr_id, tlv_id) CONSTRAINT pk_tr_tlv_awd_ctr );
ALTER TABLE dtaaladv.tr_tlv_awd_tks
	ADD CONSTRAINT ( PRIMARY KEY (tks_id, tlv_id) CONSTRAINT pk_tr_tlv_awd_tks );
ALTER TABLE dtaaladv.td_opr_opladen_tu
	ADD CONSTRAINT ( UNIQUE (orp_id) CONSTRAINT uq_td_opr_opladen_tu_orp_id );
ALTER TABLE dtaaladv.td_taalunie_xml
	ADD CONSTRAINT ( UNIQUE (ophaaldatum) CONSTRAINT uq_td_taalunie_ophaaldatum );
ALTER TABLE dtaaladv.bts_tks
	ADD CONSTRAINT ( FOREIGN KEY()
	REFERENCES dtaaladv.td_tks(tks_id) CONSTRAINT r153_199 );
ALTER TABLE dtaaladv.bts_tlv
	ADD CONSTRAINT ( FOREIGN KEY()
	REFERENCES dtaaladv.td_tlv_awd(tlv_id) CONSTRAINT r152_197 );
ALTER TABLE dtaaladv.td_ctt
	ADD CONSTRAINT ( FOREIGN KEY()
	REFERENCES dtaaladv.tp_zgv(zgv_id) CONSTRAINT r131_185 );
ALTER TABLE dtaaladv.td_frq_ozk
	ADD CONSTRAINT ( FOREIGN KEY()
	REFERENCES dtaaladv.tp_zgv(zgv_id) CONSTRAINT r133_186 );
ALTER TABLE dtaaladv.td_nsg_ref
	ADD CONSTRAINT ( FOREIGN KEY()
	REFERENCES dtaaladv.tp_nsw(nsw_id) CONSTRAINT r130_184 );
ALTER TABLE dtaaladv.td_ntt
	ADD CONSTRAINT ( FOREIGN KEY()
	REFERENCES dtaaladv.td_tav(tav_id) CONSTRAINT r129_183 );
ALTER TABLE dtaaladv.td_opr
	ADD CONSTRAINT ( FOREIGN KEY()
	REFERENCES dtaaladv.tp_dgp(dgp_id) CONSTRAINT r128_182 );
ALTER TABLE dtaaladv.td_opr
	ADD CONSTRAINT ( FOREIGN KEY()
	REFERENCES dtaaladv.tp_dmn(dmn_id) CONSTRAINT r128_181 );
ALTER TABLE dtaaladv.td_opr
	ADD CONSTRAINT ( FOREIGN KEY()
	REFERENCES dtaaladv.tr_drb(drb_id) CONSTRAINT r128_180 );
ALTER TABLE dtaaladv.td_opr
	ADD CONSTRAINT ( FOREIGN KEY()
	REFERENCES dtaaladv.tp_mdm(mdm_id) CONSTRAINT r128_179 );
ALTER TABLE dtaaladv.td_opr
	ADD CONSTRAINT ( FOREIGN KEY()
	REFERENCES dtaaladv.td_tav(tav_id) CONSTRAINT r128_178 );
ALTER TABLE dtaaladv.td_opr
	ADD CONSTRAINT ( FOREIGN KEY()
	REFERENCES dtaaladv.tp_gmn(gmn_id) CONSTRAINT r128_177 );
ALTER TABLE dtaaladv.td_opr
	ADD CONSTRAINT ( FOREIGN KEY()
	REFERENCES dtaaladv.tp_orp_sts(orp_sts_cd) CONSTRAINT r128_176 );
ALTER TABLE dtaaladv.td_opr
	ADD CONSTRAINT ( FOREIGN KEY()
	REFERENCES dtaaladv.tp_hkm(hkm_id) CONSTRAINT r128_175 );
ALTER TABLE dtaaladv.td_opr_opladen_tu
	ADD CONSTRAINT ( FOREIGN KEY()
	REFERENCES dtaaladv.td_opr(orp_id) CONSTRAINT r136_190 );
ALTER TABLE dtaaladv.td_tav
	ADD CONSTRAINT ( FOREIGN KEY()
	REFERENCES dtaaladv.tp_dmn(dmn_id) CONSTRAINT r106_163 );
ALTER TABLE dtaaladv.td_tks
	ADD CONSTRAINT ( FOREIGN KEY()
	REFERENCES dtaaladv.tp_rvt(rvt_id) CONSTRAINT fk_td_tks_tp_rvt );
ALTER TABLE dtaaladv.td_tks
	ADD CONSTRAINT ( FOREIGN KEY()
	REFERENCES dtaaladv.td_opr(orp_id) CONSTRAINT fk_td_tks_td_opr );
ALTER TABLE dtaaladv.td_tlv_awd
	ADD CONSTRAINT ( FOREIGN KEY()
	REFERENCES dtaaladv.tp_rvt(rvt_id) CONSTRAINT fk_td_tlv_awd_tp_rvt );
ALTER TABLE dtaaladv.td_tsb
	ADD CONSTRAINT ( FOREIGN KEY()
	REFERENCES dtaaladv.td_tks(tks_id) CONSTRAINT fk_td_tsb_td_tks );
ALTER TABLE dtaaladv.tp_dgp
	ADD CONSTRAINT ( FOREIGN KEY()
	REFERENCES dtaaladv.tp_dgp_alg(dgp_alg_id) CONSTRAINT r108_164 );
ALTER TABLE dtaaladv.tp_dgp_alg
	ADD CONSTRAINT ( FOREIGN KEY()
	REFERENCES dtaaladv.tp_dmn(dmn_id) CONSTRAINT r109_165 );
ALTER TABLE dtaaladv.tp_gmn
	ADD CONSTRAINT ( FOREIGN KEY()
	REFERENCES dtaaladv.tp_lnd(lnd_cd) CONSTRAINT r111_166 );
ALTER TABLE dtaaladv.tp_nsw
	ADD CONSTRAINT ( FOREIGN KEY()
	REFERENCES dtaaladv.tp_ctg_bgf(ctg_bgf_id) CONSTRAINT r126_174 );
ALTER TABLE dtaaladv.tr_ctr
	ADD CONSTRAINT ( FOREIGN KEY()
	REFERENCES dtaaladv.tr_ctr(ctr_id) CONSTRAINT r125_173 );
ALTER TABLE dtaaladv.tr_drb
	ADD CONSTRAINT ( FOREIGN KEY()
	REFERENCES dtaaladv.tp_sbn(sbn_id) CONSTRAINT r120_168 );
ALTER TABLE dtaaladv.tr_drb
	ADD CONSTRAINT ( FOREIGN KEY()
	REFERENCES dtaaladv.tp_mdm(mdm_id) CONSTRAINT r120_167 );
ALTER TABLE dtaaladv.tr_tav_tgr
	ADD CONSTRAINT ( FOREIGN KEY()
	REFERENCES dtaaladv.td_tav(tav_id) CONSTRAINT r121_170 );
ALTER TABLE dtaaladv.tr_tav_tgr
	ADD CONSTRAINT ( FOREIGN KEY()
	REFERENCES dtaaladv.tp_tgr(tgr_id) CONSTRAINT r121_169 );
ALTER TABLE dtaaladv.tr_tks_ctr
	ADD CONSTRAINT ( FOREIGN KEY()
	REFERENCES dtaaladv.tr_ctr(ctr_id) CONSTRAINT r122_171 );
ALTER TABLE dtaaladv.tr_tlv_awd_ctr
	ADD CONSTRAINT ( FOREIGN KEY()
	REFERENCES dtaaladv.tr_ctr(ctr_id) CONSTRAINT r123_172 );
